# Generated by Claude Code — sync models with current state
# create_time column already exists in DB (added by previous auto-migrate),
# so use SeparateDatabaseAndState to avoid DuplicateColumn error.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20260112_1630'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='create_time',
                    field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='录入时间'),
                ),
            ],
            # 数据库已有该列，无需重复添加
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', '名著书籍'), ('pens', '书写工具'), ('papers', '本册纸品'), ('stationery', '学生文具'), ('correction', '修正粘合'), ('others', '其他用品')], default='others', max_length=20, verbose_name='分类'),
        ),
    ]
