# Generated by Claude Code — sync models with current state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20260112_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='录入时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', '名著书籍'), ('pens', '书写工具'), ('papers', '本册纸品'), ('stationery', '学生文具'), ('correction', '修正粘合'), ('others', '其他用品')], default='others', max_length=20, verbose_name='分类'),
        ),
    ]
