# Generated by Django 4.2.30 on 2026-06-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_product_create_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车管理'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品明细'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.order', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='录入时间'),
        ),
        migrations.DeleteModel(
            name='SaleRecord',
        ),
    ]
