"""
Django settings for yide project.

Generated by 'django-admin startproject' using Django 3.2.23 (migrated to 5.2.15).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import warnings
from pathlib import Path
from urllib.parse import urlparse


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ⚠️ 生产环境必须设置 DJANGO_SECRET_KEY 环境变量，不要使用默认值！
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    warnings.warn(
        "DJANGO_SECRET_KEY 未设置，使用不安全的开发用默认密钥，请勿用于生产环境！"
    )
    SECRET_KEY = 'insecure-dev-key-do-not-use-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    '.vercel.app',
    '.now.sh',
    '.pages.dev',
    '.edgeone.cool',
    '.edgeone.dev',
    '.dpdns.org',
    'localhost',
    '192.168.1.138',
    'yide.dpdns.org',
]

WECHAT_APPID = os.environ.get('WECHAT_APPID', '')
WECHAT_SECRET = os.environ.get('WECHAT_SECRET', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yide.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yide.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
CLOUD_DATABASE_URL = os.environ.get('CLOUD_DATABASE_URL')
# 检测 psycopg 是否可用（EdgeOne 构建可能未正确安装依赖）
_psycopg_ok = False
if CLOUD_DATABASE_URL:
    try:
        import psycopg
        _psycopg_ok = True
    except ImportError:
        try:
            import psycopg2
            _psycopg_ok = True
        except ImportError:
            # 尝试将常见 pip 安装目录加入路径后重试
            import sys as _sys, site as _site
            for _p in ['/var/user/.venv/lib/python3.10/site-packages',
                       '/var/user/.local/lib/python3.10/site-packages',
                       '/var/lang/python310/lib/python3.10/site-packages']:
                if os.path.isdir(_p) and _p not in _sys.path:
                    _site.addsitedir(_p)
            try:
                import psycopg
                _psycopg_ok = True
            except ImportError:
                try:
                    import psycopg2
                    _psycopg_ok = True
                except ImportError:
                    pass

if CLOUD_DATABASE_URL and _psycopg_ok:
    url = urlparse(CLOUD_DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path.lstrip('/'),
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port or 5432,
            'OPTIONS': {'sslmode': 'require'},
        }
    }
else:
    if CLOUD_DATABASE_URL and not _psycopg_ok:
        import warnings as _w
        _w.warn('psycopg/psycopg2 不可用，降级使用 SQLite（数据不会持久化！）')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 把 Session 存储从数据库转移到浏览器客户端加密 Cookie
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
