# Generated by Django 3.2.23 on 2026-01-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条形码')),
                ('name', models.CharField(max_length=100, verbose_name='文具名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品管理',
            },
        ),
    ]
