# Generated by Django 3.2.23 on 2026-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_salehistory_salerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信OpenID')),
                ('name', models.CharField(max_length=50, verbose_name='备注名称')),
            ],
        ),
        migrations.AlterModelOptions(
            name='salehistory',
            options={'verbose_name': '销售记录', 'verbose_name_plural': '销售历史'},
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='销售时间'),
        ),
    ]
