# Generated by Django 3.2.23 on 2026-01-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20260112_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', '名著书籍'), ('pens', '各类笔'), ('erasers', '橡皮修正'), ('others', '其他文具')], default='others', max_length=20, verbose_name='分类'),
        ),
    ]
