# Generated by Django 3.2.23 on 2026-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '商城订单', 'verbose_name_plural': '商城订单管理'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_sn',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待取货'), (1, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
